on:
  push:
    branches:
      - release
name: Deploy to Github Pages
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: dist
          BUILD_SCRIPT: npm install && npm run build
          CNAME: garrit.xyz
